const ACTIONS = {
    TOGGLE_MENU: "TOGGLE_MENU",
    TOGGLE_LIST: "TOOGLE_LIST",
    REVEAL_MORE: "REVEAL_MORE",
    UPDATE_MODE: "UPDATE_MODE",
    COMMIT_MODE: "COMMIT_MODE",
    SLIDER_DONE: "SLIDER_DONE",
    SLIDER_PUSH: "SLIDER_PUSH"
};
export default ACTIONS;